vendor/cmd/go: skip TestExecutableGOROOT
This test appears to have been broken by https://golang.org/cl/104975.

Updates golang/go#24694.
Updates golang/go#25501.

Before:

~/src/golang.org/x/vgo/vendor/cmd/go$ go test -run=TestExecutableGOROOT .
--- FAIL: TestExecutableGOROOT (0.15s)
    --- FAIL: TestExecutableGOROOT/RuntimeGoroot (0.00s)
        go_test.go:4598: /tmp/gotest104327550/new/bin/go run testdata/print_goroot.go: exit status 1, vgo requires Go 1.10 but VGOROOT=/tmp/gotest104327550/new is not a Go 1.10 source tree
FAIL
FAIL    golang.org/x/vgo/vendor/cmd/go  1.730s

After:

~/src/golang.org/x/vgo/vendor/cmd/go$ go test -run=TestExecutableGOROOT .
ok      golang.org/x/vgo/vendor/cmd/go  2.870s

Change-Id: I155a1344ec704c53d3678390cafc1ad33d1a338b
Reviewed-on: https://go-review.googlesource.com/116615
Reviewed-by: Russ Cox <rsc@golang.org>