cmd/go/internal/modfetch: update expected errors in TestCodeRepo
Updates golang/go#25501.

Before:

--- FAIL: TestCodeRepo (20.13s)
    --- FAIL: TestCodeRepo/github.com_rsc_vgotest1_v2/v2.0.0 (0.47s)
        coderepo_test.go:424: repo.Zip("v2.0.0"): missing or invalid go.mod, want error "missing go.mod"
    --- FAIL: TestCodeRepo/github.com_rsc_vgotest1_v2/80d85 (0.34s)
        coderepo_test.go:409: repo.GoMod("v2.0.0-20180219231006-80d85c5d4d17"): missing or invalid go.mod, want "missing go.mod"
        coderepo_test.go:424: repo.Zip("v2.0.0-20180219231006-80d85c5d4d17"): missing or invalid go.mod, want error "missing go.mod"
    --- FAIL: TestCodeRepo/github.com_rsc_vgotest1_v54321/80d85 (0.28s)
        coderepo_test.go:424: repo.Zip("v54321.0.0-20180219231006-80d85c5d4d17"): missing or invalid go.mod, want error "missing go.mod"
vgo: lookup code.google.com/p/go-uuid/uuid: unknown module code.google.com/p/go-uuid/uuid: no go-import tags

After:

ok      golang.org/x/vgo/vendor/cmd/go/internal/modfetch        123.433s

Change-Id: I1263af1104b36b519ab9e79c74bb8c2eed05797e
Reviewed-on: https://go-review.googlesource.com/119075
Reviewed-by: Daniel Theophanes <kardianos@gmail.com>