vendor/cmd/go/internal/modfetch: update gopkg.in requirements in TestConvertLegacyConfig
Support for major-version parsing for gopkg.in dependencies was
improved in CL 107658, but TestConvertLegacyConfig was apparently not
updated to reflect that.

Updates golang/go#25501.

Before:

--- FAIL: TestConvertLegacyConfig (32.51s)
    --- FAIL: TestConvertLegacyConfig/github.com_docker_distribution_v0.0.0-20150410205453-85de3967aa93 (0.00s)
        convert_test.go:102: golden:23: invalid module: gopkg.in/yaml.v2 should be v2, not v0 (v0.0.0-20150116202057-bef53efd0c76)

After:

--- PASS: TestConvertLegacyConfig (40.00s)
    --- PASS: TestConvertLegacyConfig/github.com_docker_distribution_v0.0.0-20150410205453-85de3967aa93 (40.00s)

Change-Id: Ied0121e78b43355f6349684f1e1836da9e587374
Reviewed-on: https://go-review.googlesource.com/117115
Reviewed-by: Russ Cox <rsc@golang.org>